### ISSUE TITLE
Sobre o sensor de temperatura

### ISSUE THREAD

**Issue by pksm** [renanlino/wearablePython-galileo#1]
Desculpa colocar isso na issues, na verdade é uma dúvida.
Lendo o código do getTemp.py, eu não entendi em que momento está sendo feita a leitura da temperatura. O código de leitura propriamente dito usa alguma biblioteca para se comunicar com o I/O  da Galileo (como a biblioteca MRAA)?
Obrigada.
E desculpa novamente colocar isso em issues.

**Comment by renanlino** [comment]
Oi, pksm!
Essa biblioteca faz a comunicação via bluetooth com o kit wearable da Telefônica (http://iot.telefonicabeta.com/kit-iot-wearable/)
O código não usa a mraa pois o sensor de temperatura está conectado ao wearable, e não à Galileo. O que o script faz é enviar o comando #TE0000 via bluetooth e aguardar a resposta:
command = "#TE0000\n\r"
bleDevice.char_write(bleHandler, bytearray(command), wait_for_response = True)
